FROM golang:1.11-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

RUN apk add --no-cache git

ADD . /
RUN cd /demo/docker && make evm-xgo

# Pull Geth into a second stage deploy container
FROM scratch

COPY --from=builder /go-ethereum/build/bin/geth /bin/evm

ENV HOME=/

ENTRYPOINT ["/bin/evm", "solo"]

EXPOSE 8080 8545 8546